name: KeepActionAlive
on:
  schedule:
    - cron: "0 0 1 * *"   # 每月1号
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: 保活
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "chore: keep actions alive"
          git push https://x-access-token:${{ secrets.MIYOUQIAN_TOKEN }}@github.com/${{ github.repository }}.git
